version: '3'
services:
  qb:
    # build:
    #   context: .
    image: docker.io/entilzha/quizbowl:0.1
    ports:
      - "4861:4861"
    volumes:
      - ./src/:/src
      - ./data/:/src/data
    command: ["bash", "run.sh"]
    environment:
      - "COMPOSE_CONVERT_WINDOWS_PATHS=1"
  eval:
    image: docker.io/entilzha/quizbowl:0.1

    # build:
    #   context: .
    volumes:
      - ./src/:/src
      - ./data/:/src/data
      - ./:/eval
    command: [
      "python", "/eval/evaluate.py",
      "--curve-pkl", "/eval/curve_pipeline.pkl",
      "--wait", "5",
      "--hostname", "qb",
      "--norun-web",
      "--char_step_size", "600",
      "data/qanta.dev.2018.04.18.json"
    ]
    depends_on:
      - "qb"
    environment:
      - "PYTHONUNBUFFERED=1"
      - "COMPOSE_CONVERT_WINDOWS_PATHS=1"
